#!/bin/bash

# Make sure your Android device is plugged in and accessible over adb.

#### Remember to enable virtual displays in xorg by adding the following to your configuration (e.g. /usr/share/X11/xorg.conf.d/20-virtual.conf)
# Section "Device"
#    Identifier "intelgpu0"
#    Driver "intel"
#    Option "VirtualHeads" "1"
#EndSection
#### If you use AMD or Nvidia, change the Identifier and Driver options to match your GPU.


# 1280×800, 1440×900, 1680×1050, 1920×1200 and 2560×1600
W=1200      # Virtual display width
H=1920      # Virtual display height
FPS=60
O=VIRTUAL1  # The name of the virtual display (check using xrandr)
P=eDP1      # The name of your physical display (check using xrandr)
PW="$(xrandr --current | grep \* | awk '{print $1;}' | cut -d x -f 1)"

# Create the virtual display
gtf $W $H $FPS | sed '3q;d' | sed 's/Modeline//g' | xargs xrandr --newmode
gtf $W $H $FPS | sed '3q;d' | sed 's/Modeline//g' | awk '{print $1;}' | sed 's/^.\(.*\).$/\1/' | xargs xrandr --addmode $O
# gtf $W $H 60 | sed '3q;d' | sed 's/Modeline//g' | awk '{print $1;}' | sed 's/^.\(.*\).$/\1/'
# is outputting 2560x1600_60.00
gtf $W $H $FPS | sed '3q;d' | sed 's/Modeline//g' | awk '{print $1;}' | sed 's/^.\(.*\).$/\1/' | xargs xrandr --output $O --left-of $P --mode
# gtf $W $H 60 | sed '3q;d' | sed 's/Modeline//g' | awk '{print $1;}' | sed 's/^.\(.*\).$/\1/' | xargs xrandr --output $O --left-of $P --rotate left --mode
    
# Forward the VNC port to your device and start a VNC session
adb reverse tcp:5900 tcp:5900
# x11vnc -localhost -clip ${W}x${H}+${PW}+0
x11vnc -localhost -clip ${W}x${H}+0+0

# When the session ends, turn off the virtual display
xrandr --output $O --off
